### ISSUE TITLE
another potentially interesting open-source ELN

### ISSUE THREAD

**Issue by ltalirz** [neo-chem/awesome-chemical-data#9]
https://www.elabftw.net/
https://github.com/elabftw/elabftw

**Comment by ml-evs** [comment]
Thanks for the links @ltalirz, I'll make a PR that adds them. Do you have any interest in being added to the Slack/discussions described at [neo-chem/org](https://github.com/neo-chem/org)?

**Comment by ltalirz** [comment]
> Do you have any interest in being added to the Slack/discussions described at [neo-chem/org](https://github.com/neo-chem/org)?

Sure, happy to be added (just as an observer for the time being).

**Comment by ml-evs** [comment]
Invited your EPFL address, let me know if you would rather use another
